export const EMBEDED_POSTS = [
  {
    post: "https://www.reddit.com/r/juresanguinis/comments/1qq310v/i_just_wanted_to_say_something/",
    title: "I just wanted to say something",
    by: "https://www.reddit.com/user/LiterallyTestudo/",
    user: "u/LiterallyTestudo",
    in: "https://www.reddit.com/r/juresanguinis/",
    sub: "juresanguinis",
    tag: "highlight",
  },
  {
    post: "https://www.reddit.com/r/juresanguinis/comments/1r01t4y/campobasso_third_constitutional_court_referral/",
    title: "Campobasso third Constitutional Court Referral: Full Text and Analysis",
    by: "https://www.reddit.com/user/Desperate-Ad-5539/",
    user: "u/Desperate-Ad-5539",
    in: "https://www.reddit.com/r/juresanguinis/",
    sub: "juresanguinis",
    tag: "highlight",
  },
  {
    post: "https://www.reddit.com/r/juresanguinis/comments/1r14fys/very_good_cnn_article_on_upcoming_constitutional/",
    title: "Very good CNN article on upcoming constitutional court hearing about Tajani Decree",
    by: "https://www.reddit.com/user/AmberSnow1727/",
    user: "u/AmberSnow1727",
    in: "https://www.reddit.com/r/juresanguinis/",
    sub: "juresanguinis",
    tag: "highlight",
  },
  {
    post: "https://www.reddit.com/r/juresanguinis/comments/1qx4cc5/friends_italian_citizenship_acknowledged/",
    title: "Friends! Italian citizenship acknowledged!",
    by: "https://www.reddit.com/user/pinotJD/",
    user: "u/pinotJD",
    in: "https://www.reddit.com/r/juresanguinis/",
    sub: "juresanguinis",
    tag: "highlight",
  },
  {
    post: "https://www.reddit.com/r/juresanguinis/comments/1r1zyyb/supreme_court_dates_update/",
    title: "Supreme Court dates update",
    by: "https://www.reddit.com/user/LiterallyTestudo/",
    user: "u/LiterallyTestudo",
    in: "https://www.reddit.com/r/juresanguinis/",
    sub: "juresanguinis",
    tag: "highlight",
  },
  {
    post: "https://www.reddit.com/r/juresanguinis/comments/1m348m8/i_got_my_passport/",
    title: "I got my passport!",
    by: "https://www.reddit.com/user/scanese/",
    user: "u/scanese",
    in: "https://www.reddit.com/r/juresanguinis/",
    sub: "juresanguinis",
    tag: "top",
  },
  {
    post: "https://www.reddit.com/r/juresanguinis/comments/1mfg7mf/after_4_years_i_finally_got_it/",
    title: "After 4 years I finally got it",
    by: "https://www.reddit.com/user/CabinetKind6935/",
    user: "u/CabinetKind6935",
    in: "https://www.reddit.com/r/juresanguinis/",
    sub: "juresanguinis",
    tag: "top",
  },
  {
    post: "https://www.reddit.com/r/juresanguinis/comments/1joubu7/whats_happening_in_rome/",
    title: "What's happening in Rome",
    by: "https://www.reddit.com/user/FSItalianCitizenship/",
    user: "u/FSItalianCitizenship",
    in: "https://www.reddit.com/r/juresanguinis/",
    sub: "juresanguinis",
    tag: "top",
  },
  {
    post: "https://www.reddit.com/r/juresanguinis/comments/1jlxx7v/megathread_italy_tightens_rules_on_citizenship/",
    title: "MEGATHREAD: Italy Tightens Rules on Citizenship for Descendants Abroad",
    by: "https://www.reddit.com/user/LiterallyTestudo/",
    user: "u/LiterallyTestudo",
    in: "https://www.reddit.com/r/juresanguinis/",
    sub: "juresanguinis",
    tag: "top",
  },
  {
    post: "https://www.reddit.com/r/juresanguinis/comments/1q7w11r/finally_recognized_it_took_20_freakin_years/",
    title: "Finally recognized. It took 20 freakin' years.",
    by: "https://www.reddit.com/user/Last-Web5260/",
    user: "u/Last-Web5260",
    in: "https://www.reddit.com/r/juresanguinis/",
    sub: "juresanguinis",
    tag: "top",
  },
  {
    post: "https://www.reddit.com/r/juresanguinis/comments/1r9zkh2/hearing_date_set_for_mantova_corte_costituzionale/",
    title: "Hearing date set for Mantova Corte Costituzionale referral",
    by: "https://www.reddit.com/user/CakeByThe0cean/",
    user: "u/CakeByThe0cean",
    in: "https://www.reddit.com/r/juresanguinis/",
    sub: "juresanguinis",
    tag: "hot",
  },
  {
    post: "https://www.reddit.com/r/juresanguinis/comments/1r63rdo/weekly_discussion_post_recent_changes_to_js_laws/",
    title: "Weekly Discussion Post - Recent Changes to JS Laws - February 16, 2026",
    by: "https://www.reddit.com/user/AutoModerator/",
    user: "u/AutoModerator",
    in: "https://www.reddit.com/r/juresanguinis/",
    sub: "juresanguinis",
    tag: "hot",
  },
  {
    post: "https://www.reddit.com/r/juresanguinis/comments/1ra50l0/a_redditors_abridged_guide_to_qualifying_after/",
    title: "A Redditor's Abridged Guide to Qualifying after L74, volume 1",
    by: "https://www.reddit.com/user/Equal_Apple_Pie/",
    user: "u/Equal_Apple_Pie",
    in: "https://www.reddit.com/r/juresanguinis/",
    sub: "juresanguinis",
    tag: "hot",
  },
  {
    post: "https://www.reddit.com/r/juresanguinis/comments/1racgxq/prenotmi_houston_offline_feb_2325/",
    title: "Prenot@mi Houston offline Feb 23-25",
    by: "https://www.reddit.com/user/flilmawinstone/",
    user: "u/flilmawinstone",
    in: "https://www.reddit.com/r/juresanguinis/",
    sub: "juresanguinis",
    tag: "hot",
  },
  {
    post: "https://www.reddit.com/r/juresanguinis/comments/1ra7qi3/has_my_js_nyc_lawyer_been_sandbaggin_me_for_years/",
    title: "Has my JS NYC lawyer been sandbaggin' me for years??",
    by: "https://www.reddit.com/user/GhostOfJohnBelushi/",
    user: "u/GhostOfJohnBelushi",
    in: "https://www.reddit.com/r/juresanguinis/",
    sub: "juresanguinis",
    tag: "hot",
  },
];